#!/bin/bash
source "$(dirname "$0")/../cookbook"

VERSION=2.88
PLATFORMS="android-aarch64 android-x86_64 linux-x86_64 osx-x86_64 windows-x86_64"
CMAKE_FLAGS="
  -DBUILD_PYBULLET=OFF
  -DCMAKE_VERBOSE_MAKEFILE=ON
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  -DUSE_DOUBLE_PRECISION=ON
  -DCMAKE_BUILD_TYPE=Release
  -DBUILD_OPENGL3_DEMOS=OFF
  -DBUILD_BULLET2_DEMOS=OFF
  -DBUILD_EXTRAS=OFF
  -DBUILD_UNIT_TESTS=OFF
"

prep() {
  prep_tarball https://github.com/bulletphysics/bullet3/archive/$VERSION.tar.gz
}

recipe() {
  case $1 in
  android-aarch64|android-x86_64)
    cmake "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX" \
      -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN_FILE" \
      -DANDROID_NDK="$ANDROID_NDK_HOME" \
      -DANDROID_ABI=$ANDROID_ABI \
      -DANDROID_PLATFORM=$ANDROID_PLATFORM
    make -j $(nproc 2>/dev/null || echo 12)
    make install
    ;;

  linux-x86_64|osx-x86_64)
    cmake "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX"
    make -j $(nproc 2>/dev/null || echo 12)
    make install
    ;;

  windows-x86_64)
    cmake -G "Visual Studio 15 2017" -A x64 $CMAKE_FLAGS $SRC
    MSBuild.exe BULLET_PHYSICS.sln //p:Configuration=Release;Platform=x64

    # collect headers
    mkdir -p "$PREFIX/include"
    rsync -qavm --include='*.h' --include='*.hpp' -f 'hide,! */' \
      "$SRC/src/" "$PREFIX/include"

    # collect and merge libraries
    cd "$BLD/lib/Release"
    mkdir -p "$PREFIX/lib"
    WIN_OUTLIB=$(echo "$PREFIX/lib/libBullet.lib" | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')
    PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build:$PATH" cmd //C "vcvarsall.bat amd64 && lib /OUT:$WIN_OUTLIB *.lib"
    ;;
  *)
    exit 1
    ;;
  esac
}

begin