#!/bin/bash
source "$(dirname "$0")/../cookbook"

VERSION=1.6.37
PLATFORMS="android-aarch64 android-x86_64 linux-x86_64 osx-x86_64 windows-x86_64"
CMAKE_FLAGS="
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_VERBOSE_MAKEFILE=ON
  -DPNG_TESTS=NO
"

prep() {
  prep_tarball https://download.sourceforge.net/libpng/libpng-$VERSION.tar.gz
  prep_patch compile-fix
}

recipe() {
  case $1 in
  android-aarch64|android-x86_64)
    cmake "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX" \
      -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN_FILE" \
      -DANDROID_NDK="$ANDROID_NDK_HOME" \
      -DANDROID_ABI=$ANDROID_ABI \
      -DANDROID_PLATFORM=$ANDROID_PLATFORM
    make #-j $(nproc 2>/dev/null || echo 12)
    make install
    ;;
    
  linux-x86_64|osx-x86_64)
    cmake "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX"
    make -j $(nproc 2>/dev/null || echo 12)
    make install
    ;;

  windows-x86_64)
    cmake -G "Visual Studio 15 2017" -A x64 "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX"
    MSBuild.exe libpng.sln //p:Configuration=Release;Platform=x64

    # collect headers
    mkdir -p "$PREFIX/include/libpng"
    cp "$SRC/png.h" "$SRC/pngconf.h" pnglibconf.h "$PREFIX/include/libpng"

    # collect library
    mkdir -p "$PREFIX/lib"
    cp Release/libpng16_static.lib "$PREFIX/lib/libpng.lib"
    cp Release/libpng16.dll "$PREFIX/lib"
    cp Release/libpng16.exp "$PREFIX/libpng_imp.exp"
    cp Release/libpng16.lib "$PREFIX/libpng_imp.lib"
    ;;
  *)
    exit 1
    ;;
  esac
}

begin
