#!/bin/bash
source "$(dirname "$0")/../cookbook"

VERSION=master
PLATFORMS="android-aarch64 android-x86_64 linux-x86_64 osx-x86_64 windows-x86_64"
CMAKE_FLAGS="
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_VERBOSE_MAKEFILE=ON
  -DALSOFT_TESTS=NO
  -DALSOFT_UTILS=NO
"

prep() {
  prep_git https://github.com/kcat/openal-soft.git
}

recipe() {
  case $1 in
  android-aarch64|android-x86_64)
     cmake "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX" \
      -DANDROID_NDK="$ANDROID_NDK_HOME" \
      -DANDROID_ABI=$ANDROID_ABI \
      -DANDROID_PLATFORM=$ANDROID_PLATFORM
    make -j $(nproc 2>/dev/null || echo 12)
    make install
    ;;

  linux-x86_64|osx-x86_64)
    cmake "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX"
    make -j $(nproc 2>/dev/null || echo 12)
    make install
    ;;

  windows-x86_64)
    cmake -G "Visual Studio 15 2017" -A x64 "$SRC" $CMAKE_FLAGS \
      -DCMAKE_PREFIX_PATH="$PREFIX" \
      -DCMAKE_INSTALL_PREFIX="$PREFIX"
    MSBuild.exe openal.sln //p:Configuration=Release;Platform=x64

    # collect headers
    mkdir -p "$PREFIX/include"
    rsync -qavm --include='*.h' --include='*.hpp' --exclude='internal/' -f 'hide,! */' \
      "$SRC/include/" "$PREFIX/include"

    # collect library
    mkdir -p "$PREFIX/lib"
    cp Release/OpenAL32.dll "$PREFIX/lib"
    cp Release/OpenAL32.exp "$PREFIX/lib/OpenAL32_imp.exp"
    cp Release/OpenAL32.lib "$PREFIX/lib/OpenAL32_imp.lib"
    ;;
  *)
    exit 1
    ;;
  esac
}

begin